Korrektur libusb Simon

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -3,7 +3,7 @@
 # Parameterize
 PYTHON_VERSION=3.7.10
 BUILDDIR=/tmp/electrum-build
-PACKAGE=electrum-doi
+PACKAGE=electrum
 GIT_REPO=https://github.com/spesmilo/electrum
 
 export GCC_STRIP_BINARIES="1"
@@ -115,12 +115,15 @@ info "generating locale"
 ) || fail "failed generating locale"
 
 
-info "Downloading libusb..."
-curl https://homebrew.bintray.com/bottles/libusb-1.0.23.high_sierra.bottle.tar.gz | \
-tar xz --directory "$BUILDDIR"
-cp "$BUILDDIR/libusb/1.0.23/lib/libusb-1.0.dylib" contrib/osx
-echo "caea266f3fc3982adc55d6cb8d9bad10f6e61f0c24ce5901aa1804618e08e14d  contrib/osx/libusb-1.0.dylib" | \
-    shasum -a 256 -c || fail "libusb checksum mismatched"
+#info "Downloading libusb..."
+#curl https://homebrew.bintray.com/bottles/libusb-1.0.23.high_sierra.bottle.tar.gz | \
+#tar xz --directory "$BUILDDIR"
+#cp "$BUILDDIR/libusb/1.0.23/lib/libusb-1.0.dylib" contrib/osx
+#echo "caea266f3fc3982adc55d6cb8d9bad10f6e61f0c24ce5901aa1804618e08e14d  contrib/osx/libusb-1.0.dylib" | \
+#    shasum -a 256 -c || fail "libusb checksum mismatched"
+
+brew install libusb
+cp /usr/local/Cellar/libusb/1.0.24/lib/libusb-1.0.0.dylib ~/electrum-doi/contrib/osx/libusb-1.0.dylib
 
 info "Preparing for building libsecp256k1"
 brew install autoconf automake libtool
